### PR TITLE
Adding poetry and Django test structure

### PR DESCRIPTION
**Pull request by rjauquet**
Added some ideas for test infrastructure. Open to other suggestions! 

After installing [poetry](https://github.com/sdispater/poetry):
```
poetry install
poetry run ./manage.py test
```

The test isn't really checking anything important but I wanted to make sure all the importing logic and calling worked.

### CODE REVIEW

**Comment by ramonsaraiva** [comment]
That's pretty cool. I'm not really familar with `poetry`, could you explain me what are those dependencies in that `lock` file?

**Comment by rjauquet** [comment]
Yeah! Poetry is a dependency manager, and the lock file just guarantees each person setting up the code gets exactly the same dependency list on the same version on python. It's not strictly necessary but it can save some headaches for sure.

**Comment by ramonsaraiva** [comment]
Yup! I get that, but, I see there are a few dependencies already defined in the file, besides Django.
Are those dependencies of Django itself? Or they were added mistakenly?

**Comment by rjauquet** [comment]
Sorry, I misunderstood. Yes. Absolutely we don't need Pytest. I removed it now. The lock should just be sub-dependencies of Django

**Review by ramonsaraiva — APPROVED** [review]

**Comment by AhmedRedaAmin** [comment]
hey @rjauquet  can you help me out with something ?
selection_066
I can't understand why it is failing here ?
The virtualenv is part of poetry's setup AFAIK .

**Comment by rjauquet** [comment]
Yes, the poetry setup should create the virtualenv. I just tried this locally and was able to get it working. I'm wondering if poetry was installed with an incompatible version of python. Could you try sourcing into the virtualenv directly and then running ./manage.py test?

```
source /root/.cache/pypoetry/virtualenvs/django-expiry-py3.6/bin/activate
./manage.py test
```
I think is your path. How did you install poetry?

**Comment by AhmedRedaAmin** [comment]
@rjauquet , no worries , I managed to resolve it , seems when you use sudo , it instantiates the virtualenv in a different location than it normally does .

**Pull request merged**
